[project]
name = "ml-zoomcamp"
version = "0.1.0"
description = "Machine Learning Zoomcamp 2025"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "jupyter", 
  "numpy", 
  "pandas", 
  "scikit-learn", 
  "seaborn"
]
